name: test

on:
  workflow_dispatch:

env:
  PATCH_SCRIPT: patch/demo.sh
  TZ: Asia/Shanghai

jobs:
  Build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - {
              source_type: "LEDE",
              repo_url: "https://github.com/coolsnowwolf/lede.git",
              repo_branch: "master",
              config: "configs/x86_64.config",
              diy_script: "diy-full.sh",
              fix_rust: false,
              fix_golang: true,
              fix_ss_libev: false,
            }
          - {
              source_type: "ImmortalWrt",
              repo_url: "https://github.com/immortalwrt/immortalwrt",
              repo_branch: "openwrt-25.12",
              config: "configs/x86_64-immortalWrt.config",
              diy_script: "diy-full.sh",
              fix_rust: true,
              fix_golang: true,
              fix_ss_libev: false,
            }
      max-parallel: 2
      fail-fast: false

    name: 编译 ${{ matrix.source_type }} FULL 版本固件

    steps:
      - name: 检查
        uses: actions/checkout@main

      - name: 测试
        run: |
          chmod +x $PATCH_SCRIPT
          $PATCH_SCRIPT
